#!/usr/bin/env bash
# Generate — or verify — the `canonical_low<k>` family of stdlib gadgets.
#
#   scripts/gen_canonical.sh            regenerate std/canonical_low*.zkc
#   scripts/gen_canonical.sh --check    fail if any committed file has drifted
#
# `canonical_low<k>(v) -> (i0 .. i<k-1>)` extracts the k low bits of a value's
# canonical representative — the FRI query position for a domain of size 2^k.
# The argument for why it is shaped the way it is lives in the generated header
# and in docs/in-circuit-index.md; this script is about the *k*.
#
# Why a generator. Everything in the gadget except its last k lines is
# independent of k: the same 64-bit decomposition, the same canonicity check.
# Only the exposure of the low bits varies. The language has no parametric
# gadgets — a gadget's arity is part of its declaration — so the parameter has
# to live somewhere outside the language, and a committed generator whose
# output is checked is the honest place for it. Same discipline as
# scripts/fixtures.sh and `zkc doc`: generated artefacts are committed so the
# build stands alone, and a --check proves they are still what the generator
# produces.
#
# Adding a domain size is one number in WIDTHS below plus a run of this script.
set -uo pipefail
cd "$(dirname "$0")/.."

# The k values the repo commits. The examples use domains 2 and 4 (k = 1, 2);
# 3 and 4 are here so that "generalised" is a claim with evidence rather than a
# design intention. The generator itself has no upper bound short of 64.
WIDTHS=(1 2 3 4)

check=0
[ "${1:-}" = "--check" ] && check=1

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# The 64 bit names, comma-separated.
all_bits() {
  local out="b0" i
  for ((i = 1; i < 64; i++)); do out="$out, b$i"; done
  printf '%s' "$out"
}

# One 8-bit chunk of the low-half reconstruction, e.g. `b0 + 2 * b1 + ...`.
low_chunk() {
  local first=$1 i term out=""
  for ((i = first; i < first + 8; i++)); do
    if [ "$i" = 0 ]; then term="b0"; else term="$((2 ** i)) * b$i"; fi
    if [ -z "$out" ]; then out="$term"; else out="$out + $term"; fi
  done
  printf '%s' "$out"
}

gadget() {
  local k=$1 i
  local results="i0: field"
  for ((i = 1; i < k; i++)); do results="$results, i$i: field"; done

  cat <<HEADER
// canonical_low$k(v) -> (i0 .. i$((k - 1))): the $k low bit(s) of v's canonical
// representative, extracted soundly (phase 7, O — this closes the finding in
// docs/in-circuit-index.md).
//
// The use is the FRI query index: for a domain of size $((2 ** k)) the position is
// \`$(
    if [ "$k" = 1 ]; then printf 'i0'
    else
      printf 'i0'
      for ((i = 1; i < k; i++)); do printf ' + %s * i%s' "$((2 ** i))" "$i"; done
    fi
  )\`. Deriving it in-circuit is what stops a prover
// from opening a position of its choosing.
//
// GENERATED by scripts/gen_canonical.sh — edit that, not this. Only the last
// $k assertion(s) depend on the width; everything above them is the same
// decomposition and the same canonicity check for every k.
//
// Why this is not a two-line gadget. The natural binding
// \`v == index + $((2 ** k))*high\` proves determinate and is forgeable: \`high\` is free,
// so the prover reaches any index it likes. The index being the LOW BITS of v
// is a range property, and range properties are what determinacy does not see
// (examples/index_from_challenge.zkc is the cautionary version). So pin the
// range instead of asserting the relation: decompose v into all 64 of its
// bits. The reconstruction \`v == sum b_i 2^i\` leaves the prover no freedom —
// the bits ARE the representative — and the index is read off rather than
// related.
//
// One wrinkle is specific to Goldilocks, and it is why the gadget is long.
// The field wraps at p = 2^64 - 2^32 + 1, which is BELOW 2^64, so a 64-bit
// string is not a unique representative: whenever the canonical value c is
// less than 2^32 - 1, the string for c + p is also 64 bits wide and also
// satisfies the reconstruction. Its low bits differ from c's, so a prover
// could shift the query index for roughly one challenge in 2^32. Rare is not
// sound.
//
// The non-canonical strings are exactly those in [p, 2^64), and because
// p = 2^64 - 2^32 + 1 that interval has a clean description: the top 32 bits
// are all set AND the low 32 bits are not all zero. Hence the check
//
//     (all top bits set) * (low 32 bits) == 0
//
// which refuses every non-canonical string and no canonical one — including
// p - 1 = 2^64 - 2^32, whose top bits are all set and whose low half is zero.
// The all-ones test is a product of the 32 top bits: 31 multiplications, no
// advice and no case split, so the gadget stays inside the decidable core and
// needs no SMT.
//
// Bind with:  ($(
    printf 'i0'
    for ((i = 1; i < k; i++)); do printf ', i%s' "$i"; done
  )) = canonical_low$k(v);
// Goldilocks only — compile with --field goldilocks. The canonicity check is
// arithmetic about p and means nothing over another field.
gadget canonical_low$k(v: field) -> ($results) {
    advice ($(all_bits)) = bits(v);

    // The low 32 bits as a value: zero exactly when the string's low half is.
HEADER

  for ((i = 0; i < 4; i++)); do
    printf '    let lo%s = %s;\n' "$i" "$(low_chunk $((i * 8)))"
  done
  printf '    let lo = lo0 + lo1 + lo2 + lo3;\n\n'
  printf '    // ones30 == 1 exactly when every one of the top 32 bits is set.\n'
  printf '    let ones0 = b32 * b33;\n'
  for ((i = 34; i < 64; i++)); do
    printf '    let ones%s = ones%s * b%s;\n' "$((i - 33))" "$((i - 34))" "$i"
  done
  printf '\n'
  printf '    // Canonicity: a string with all top bits set may only be p - 1'"'"'s, whose\n'
  printf '    // low half is zero. Every other non-canonical string dies here.\n'
  printf '    assert ones30 * lo == 0;\n\n'
  printf '    // The low bit(s), read off the pinned decomposition.\n'
  for ((i = 0; i < k; i++)); do
    printf '    assert i%s == b%s;\n' "$i" "$i"
  done
  printf '}\n'
}

broken() {
  local k=$1 i
  local results="i0: field"
  for ((i = 1; i < k; i++)); do results="$results, i$i: field"; done
  local names="b0, b1"
  for ((i = 2; i <= k; i++)); do names="$names, b$i"; done

  cat <<HEADER
// BROKEN: i0 is constrained to be a bit, but never tied to v's decomposition —
// so both values of it satisfy every constraint and the prover picks the query
// position it prefers. This is the shape of the real bug the sound gadget
// exists to avoid; determinacy rejects it because the output is not a function
// of the input. (The subtler failure — a binding that IS determinate and still
// unsound — is examples/index_from_challenge.zkc, which no determinacy check
// can catch.)
//
// GENERATED by scripts/gen_canonical.sh.
gadget canonical_low$k(v: field) -> ($results) {
    advice ($names) = bits(v);
    assert i0 * (1 - i0) == 0;
HEADER
  for ((i = 1; i < k; i++)); do
    printf '    assert i%s == b%s;\n' "$i" "$i"
  done
  printf '}\n'
}

drift=0
for k in "${WIDTHS[@]}"; do
  gadget "$k" > "$tmp/canonical_low$k.zkc"
  broken "$k" > "$tmp/canonical_low${k}_broken.zkc"

  for pair in "canonical_low$k.zkc:std" "canonical_low${k}_broken.zkc:std/tests"; do
    file="${pair%%:*}"
    dir="${pair#*:}"
    if [ "$check" = 1 ]; then
      if ! cmp -s "$tmp/$file" "$dir/$file"; then
        echo "DRIFT    $dir/$file is not what the generator produces"
        drift=1
      else
        echo "ok       $dir/$file"
      fi
    else
      cp "$tmp/$file" "$dir/$file"
      echo "wrote    $dir/$file"
    fi
  done
done

if [ "$check" = 1 ] && [ "$drift" = 1 ]; then
  echo
  echo "Stale. Regenerate with: scripts/gen_canonical.sh"
  exit 1
fi
